import { Inter } from 'next/font/google';
import cn from 'clsx';
import { Session, getServerSession } from 'next-auth';


import GlobalNav from '@/components/global-nav';
import '@/styles/globals.css';
import Provider from '@/components/provider';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import ClientSide from './client-side';

export const metadata = {
  title: "Charlie Loong's Next App",
  description: 'Generated by create next app',
};

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html
      lang="en"
      className={cn(inter.className, '[color-scheme:dark]', 'scroll-smooth')}
    >
      <head />
      <body className="overflow-y-scroll bg-gray-1100 min-h-screen h-full w-full">
        <Provider>
          <GlobalNav />
          <div className="lg:pl-72">
            <div className="mx-auto max-w-6xl space-y-8 px-2 pt-20 lg:py-8 lg:px-8">
              {/* <div className="rounded-lg bg-vc-border-gradient p-px shadow-lg shadow-black/20">
              <div className="rounded-lg bg-black"><AddressBar /> </div>
            </div> */}

              <div className="rounded-lg shadow-lg shadow-black">
                <main className="rounded-lg bg-black p-3.5 lg:p-6 min-h-[90vh] flex max-w-6xl place-items-stretch">
                  {children}
                </main>
              </div>
              {/* <Byline className="fixed sm:hidden" /> */}
            </div>
            <ClientSide />
          </div>
        </Provider>
      </body>
    </html>
  );
}
